name: push

on:
  push:
    branches: ["main"]

jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Build and Publish head Docker image
          uses: VaultVulp/gp-docker-action@1.6.0
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              image-name: duckdns-ip-updater
              image-tag: latest
              custom-args: --platform=linux/arm64,linux/amd64